= Mangfold i samlingene – tverrfaglig forskningsstøtte og formidling
Line Nybakk Akerholt og Dan Michael Heggø, Universitetsbiblioteket i Oslo
:doctype: book
:docinfo:
:icons: font
:toc: left
:toc-title: Innholdsfortegnelse
:toclevels: 3
:sectlinks:

:leveloffset: +1

Lenker og bakgrunnsinformasjon for prosjekter omtalt på link:poster.pdf[posteren] (PDF, 1.1 MB) presentert på konferansen https://www.uib.no/ub/fagressurser/spesialsamlingene/129101/program-konferansen-spesialsamlinger-i-bibliotekene-2019[_Spesialsamlinger i bibliotekene_ (2019)].

Kilde for dette dokumentet: https://github.com/uio-library/mangfold-i-samlingene

.Abstract for posteren
[%collapsible]
====
Siden åpningen av biblioteket i 2012 har Realfagsbiblioteket vektlagt formidling og vitenskapelige foredrag for å etablere biblioteket som en arena for vitenskapelig debatt og åpenhet. Med vår tidligere erfaring som drivere av små instituttbibliotek og nære relasjon til samlinger og fag, var det nå som en større, tverrfaglig enhet, lettere å komme i kontakt med andre miljøer på UiO som også samler og formidler. Det viser seg at vi og flere av våre samarbeidspartnere mangler rammeverk for dette arbeidet. De store databasene til boksamlingene og gjenstandssamlingene egner seg ikke for de mindre samlingene som oppstår, der forskere over tid har tilpasset strukturen og metadata til sin egen forskning og undervisning. Spesialsamlingene, slik vi nå kjenner dem, lever sitt eget liv mellom bokbaser, administrative arkiver, forskningsdata, museumsbaser og formidlingsprosjekter på webservere.

Da Alma-digital dukket opp som en mulighet for å registrere metadata og digitale representasjoner for materiale utover bokformatet, ønsket vi å teste ut dette også for spesialsamlinger. I 2018-2019 gjennomførte vi flere prosjekter, hvorav noen av samlingene lot seg modellere via marc eller dublin core, mens andre fortsatt byr på utfordringer. Målet vårt er å øke forståelsen og kunnskapen om metadata for ulike typer samlinger slik at man i fremtiden kan utnytte autoritetsregistre og identifikatorer tilknyttet de etablerte basene i arbeidet med spesialsamlingene, og dermed styrke formidling, forskningsstøtte og langtidslagring av viktige ressurser.
====

= Hansteens brevsamling

https://uio-library.github.io/hansteen-brev/ +
Prosjektside med dokumentasjon: https://github.com/uio-library/hansteen-brev

Består av rundt 1500 vitenskapelige brev til https://www.ub.uio.no/fag/naturvitenskap-teknologi/astro/hansteen/biografi/[Christopher Hansteen].
Rundt _halvparten_ av brevene (707 stk.) ble scannet (med noe varierende kvalitet) og registrert i en Oracle-database gjennom et prosjekt på begynnelsen av 2000-tallet, men ble aldri publisert.

I 2018 brukte vi samlingen som https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/collectionDiscovery?vid=UIO&collectionId=81218451430002204&lang=no_NO[pilotsamling for Alma Digital].
De originale Oracle-tabellene ble arkivert som CSV-filer i et Git-repo sammen med konverteringsscriptene vi brukte for å konvertere dataene til MARC21, slik at (i) konverteringen enkelt kan gjøres om igjen ved en senere anledning om vi skulle ønske å endre på den og (ii) vi har et bedre utgangspunkt for å konvertere til et eventuelt annet format i fremtiden om vi skulle gå over til et annet system.

Siden Alma Digital ikke har muligheter for å navigere i samlingen utover enkelt søk lagde vi også en https://uio-library.github.io/hansteen-brev/[enkel presentasjonsside] for samlingen på GitHub.

== Saturn (Simple Alma Tool for URN management)

https://github.com/scriptotek/saturn +
Data: https://github.com/scriptotek/saturn-data

Alma har ikke innebygget støtte for å opprette (systemuavhengige) persistente identifikatorer.
For å bøte på dette lagde vi et enkelt verktøy for å generere URN-er for Alma-poster ved hjelp av NBs URN-API og lagre disse i MARC-postene.
Gjennom å legge både script, dokumentasjon og tabellen med koblingsnøkler åpent på GitHub _håper_ vi at noen kommer til å finne det og huske på å kjøre en oppdatering en dag i fremtiden når UBO bytter system.
Siden det innledende Alma Digital-prosjektet ble avsluttet har UBO ikke hatt en formell Alma Digital-gruppe og heller ikke et offisielt sted for å samle og sikre dokumentasjon.

= Realfagsbibliotekets arrangementsarkiv

Arkivet: http://ub-media.uio.no/arkiv/ub-live/ +
Utad: https://www.youtube.com/user/realfagsbiblioteket

Samlingen består av opptak av vitenskapsformidling, debatter og andre https://www.ub.uio.no/bibliotekene/ureal/ureal/aktiviteter.html[arrangementer] fra Realfagsbibliotekets scene og andre steder.
Inkluderer både råopptak fra flere kilder og bearbeidet/klippet materiale, samt tilknyttet materiale som plakater.

Metadata har ikke blitt registrert sentralt, men har ved hjelp av ad-hoc scripts (Blekkio) blitt samlet inn fra arrangementsbeskrivelsessider på uio.no og fra YouTube (vår _foreløpig_ primære publiseringsplattform for video).

I Alma Digital-piloten (2018) undersøkte vi muligheten for å https://bibsys-almaprimo.hosted.exlibrisgroup.com/primo-explore/collectionDiscovery?vid=UIO&collectionId=81216307230002204&lang=no_NO[innlemme samlingen i Alma Digital].
Alma Digital har grunnleggende støtte for video og gir grunnleggende organiseringsmuligheter (arrangementene kan samles i én eller flere samlinger), men vi strevde med å få til en god presentasjon. Arbeidet med importeringsscript stanset opp fordi vi ønsket å bruke Dublin Core i stedet for MARC21, men Alma hadde på daværende tidspunkt ikke støtte for redigerbare Dublin Core-profiler.
Vi savnet også mulighet for å koble Dublin Core-poster til autoritetsregistre, vi mener det ville vært en stor berikelse om opptakene kunne kobles til personautoritetsregistre (Felles autoritetsregister og Cristin), både for gjenfinning og for bidragsyternes egen del (dokumentasjon av egen formidlingsinnsats).

= Drogesamlinger

https://uio-library.github.io/drogesamlinger/ +
Prosjektside med (mangelfull) dokumentasjon: https://github.com/uio-library/drogesamlinger

Beskrivelser av to av universitetets drogesamlinger katalogisert i en FileMaker-database på Farmasøytisk institutt, men aldri publisert. Vi har arkivert og dokumentert filene i et Git-repo og konvertert dem til CSV-filer for ettertiden.
Ikke lagt i Alma Digital siden selve drogene som katalogene beskriver foreløpig ikke er avfotografert.
En enkel statisk nettside har blitt publisert sammen med dataene på GitHub.

Universitetets eldste drogekatalog, som foreligger i bokform, har blitt hurtigscannet av Museum for Universitetshistorie og https://bibsys-k.userservices.exlibrisgroup.com/view/UniversalViewer/47BIBSYS_UBO/12229760960002204#?c=0&m=0&s=0&cv=3&xywh=-721%2C-106%2C6305%2C3673[publisert i Alma Digital].

= Norske epitafier

Beskrivelser og fotografier av alle epitafier i norske kirker samlet inn ved Teologisk institutt.
Publisert i bokform, men ønskes også publisert i en søkbar base på nett med høyoppløselige, åpne bilder.
Planlagt publisert i Alma Digital i 2020.

= Samlinger i Zotero

Realfagsbiblioteket har siden 2016 brukt Zotero som verktøy for å registrere spesialsamlinger som det har vært spesiell interesse for hos ulike fagmiljøer.

== Patrick Geddes’ samling

https://www.zotero.org/groups/892331/ (åpen samling, innlogging for tilgang til vedlegg) +
Beskrivelse: https://www.ub.uio.no/fag/naturvitenskap-teknologi/bio/geddes/ +
Dokumentasjon: ["Registrering av Patrick Geddes’ samling – Rapport fra praktikant"](https://www.zotero.org/groups/892331/patrick_geddes_samling/items/84T8K9SV) (Svein Paulsen, 2017)

Samlingen består av materiale som Philip Boardman samlet på 1970-tallet i arbeidet med å formidle om  Patrick Geddes' liv og faglige budskap. Dette resulterte blant annet i biografien «The Worlds of Patrick Geddes», utgitt i 1978.

Samlingen ble registrert og beskrevet i Zotero av Svein Paulsen i 2017.

Den består av 700 registreringer, hvorav 66 bøker og 107 småtrykk. Resten er korrespondanse i original, blant annet mellom Boardman og den amerikanske kultur- og byhistorikeren Lewis Mumford, utklipp og notater. I tillegg finnes det mye materiale fra Geddes-utstillinger som Boardman arrangerte i inn- og utland.

Realfagsbiblioteket sørger for permanent og sikker oppbevaring av samlingen, og skal gjøre den tilgjengelig for interesserte. Samlingen kan lånes ut til ansvarlige institusjoner for kortere perioder etter avtale med legatets fagkomité, eller besøkes etter avtale med Realfagsbiblioteket. 

Originaldokumentene er ikke digitalisert.

== Brøggers dagbøker

https://www.zotero.org/groups/508717/ (lukket samling for inviterte brukere)

+W. C.+ Brøggers dagbøker (157 dokumenter) ble scannet og registrert i Zotero i 2016–2017.
Samlingen er foreløpig lukket fordi det er knyttet PDF-vedlegg til postene,
noe Zotero ikke tillater for åpne samlinger.
PDF-filene må derfor flyttes til Alma Digital før samlingen kan åpnes.

== Geologiske manuskripter

https://www.zotero.org/groups/704502/ (lukket samling for inviterte brukere)

Geologiske manuskripter (228 dokumenter) ble registrert i Zotero (og delvis scannet) i 2016.
Samlingen er foreløpig lukket fordi det er knyttet PDF-vedlegg til postene,
noe Zotero ikke tillater for åpne samlinger.
PDF-filene må eventuelt flyttes til Alma Digital før samlingen kan åpnes.

== Ida-samlingen

https://www.zotero.org/groups/505119/ (lukket samling for inviterte brukere)

Samling av materiale (464 dokumenter: omtale i bøker, norsk og internasjonal presse, debatt, privat korrespondanse, filmer osv.) publisert som respons på lanseringen av fossilet Ida i 2009.

Mye opphavsrettsbeskyttet materiale, så samlingen kan ikke åpnes.

= Andre samlinger vi har snublet over

- https://www.ub.uio.no/fag/naturvitenskap-teknologi/informatikk/faglig/dns/[Ole-Johan Dahl, Kristen Nygaard og SIMULA]: Av/om informatikkpionerene Dahl og Nygaard og utviklingen av SIMULA: bibliografier, biografier, filmer, lydopptak, tekster spredt utover flere steder.

- Informatikkbibliotekets samling av gamle datamaskiner: Registrert i MUVs gjenstandsbase, men ikke åpent tilgjengelig.

- https://www.arkivportalen.no/entity/no-a1450-01000000006069[Forskerarkivet etter Rosseland]: avlevert til Riksarkivet.

